#ifndef __GUI_frame_decode_B__
#define __GUI_frame_decode_B__

/**
@file
Subclass of frame_decode_B, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing frame_decode_B */
class GUI_frame_decode_B : public frame_decode_B
{
	protected:
		// Handlers for frame_decode_B events.
		void frame_encode_A_OnUpdateUI( wxUpdateUIEvent& event );
		void button_load_input1_OnButtonClick( wxCommandEvent& event );
		void button_load_input2_OnButtonClick( wxCommandEvent& event );
		void button_encode_OnButtonClick( wxCommandEvent& event );
		void button_save_output_OnButtonClick( wxCommandEvent& event );
		void button_return_OnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		GUI_frame_decode_B( wxWindow* parent );
	//// end generated class members

};

#endif // __GUI_frame_decode_B__
